[package]
name = "xrayhexgenerator"
version = "2.1.0+23"
edition = "2024"

[dependencies]
gtk4 = "0.10"
libadwaita = { version = "0.8", features = ["v1_5"] }
rand = "0.8"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
